name: Bygg og deploy
on:
  push:

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
  LATEST_IMAGE: ghcr.io/${{ github.repository }}:latest

jobs:
  build:
    name: Bygg
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Generer .npmrc
        run: |
          cat <<'EOF' > .npmrc
              //npm.pkg.github.com/:_authToken=${{ secrets.READER_TOKEN }}
              @navikt:registry=https://npm.pkg.github.com/
              engine-strict=true
              EOF
      
      - name: Bygg og push Docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: teamdagpenger
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          tag: ${{ env.VERSION_TAG }}
          build_secrets: NODE_AUTH_TOKEN=${{ secrets.READER_TOKEN }}
          push_image: true
          dockerfile: Dockerfile
          docker_context: .

  deploy-dev:
    permissions:
      id-token: "write"
    name: Deploy til dev-gcp
    if: github.actor != 'dependabot[bot]'
    needs: [ build ]
    runs-on: ubuntu-latest
    environment:
      name: Development
    steps:
      - uses: actions/checkout@v6
      - uses: nais/deploy/actions/deploy@v2
        env:
          VAR: image=${{ needs.build.outputs.image }},githubSha=${{ github.sha }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/job.yaml
          VARS: .nais/vars-dev.yaml
          PRINT_PAYLOAD: true
  deploy-dev:
    permissions:
      id-token: "write"
    name: Deploy til prod-gcp
    if: github.actor != 'dependabot[bot]'
    needs: [ build ]
    runs-on: ubuntu-latest
    environment:
      name: Development
    steps:
      - uses: actions/checkout@v6
      - uses: nais/deploy/actions/deploy@v2
        env:
          VAR: image=${{ needs.build.outputs.image }},githubSha=${{ github.sha }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/job.yaml
          VARS: .nais/vars-prod.yaml
          PRINT_PAYLOAD: true